# Laboratory 5

## The Jacobian

Up until now, we've been discussing about the position and orientation of the
robot as described by transformations. However, it is of special interest to
consider the derivatives of the positions, meaning the velocities and
accelerations. This is especially important since robots can be used in
conditions where speed plays an important role: We usually want to perform a task
as fast as possible, while still making it safe for the environment around the
robot. The objective of this exercise is to define a way for calculating the
end-effector velocity as a function of the joint velocities.

### 5.1. Theoretical considerations


Velocity is defined as the first derivative of the position. When discussing the
velocity of a point, we can only have a linear velocity, since a point does not
have any specific orientation. When discussing about objects though, there is a
distinction between linear and angular velocities. The linear velocity shows us
how fast an object translates relative to a fixed frame, while the angular
velocity shows us how fast does one object rotate relative to a fixed frame.

Each of these velocities has three components, one about each of the axes of the
fixed coordinate frame. We denote the linear velocities as $ \dot{x}, \dot{y}$,
and $ \dot{z} $ and the angular velocities as $ \omega_x, \omega_y$, and $ \omega_z $.


If we define a vector containing all the end-effector velocities defined as 

\begin{equation}
   \xi = \begin{bmatrix} \dot{x} & \dot{y} & \dot{z} & \omega_x & \omega_y &
    \omega_z \end{bmatrix}^T \\
\end{equation}

we can define the relationship between end-effector and joint velocities as:

\begin{equation}
   \xi = J \dot{q} 
\end{equation}

where $ \dot{q} $ is a vector containing the velocities of the $ n $ robot
joints. For the multiplication to be feasible, $ J $ should be a matrix and it
should have dimensions $ 6 \times n $. This matrix is called the
_Jacobian_ and we can split it in two $ 3 \times n $ submatrices, one
corresponding to the angular and one to the linear velocities.

#### 5.1.1 ANGULAR velocities

Depending on the design of the robot and the types of joints that it has, it
might be able to change its orientation relative to the fixed frame. The part of
the Jacobian matrix that describes the relationship between joint velocities and
the angular velocity of the end effector is symbolised as $ J_{\omega} $ and it
is a $ 3 \times n $ matrix, where $ n $ is the number of joints.

Since prismatic joints do not produce any rotations, their contribution to the
end-effector angular velocity is zero. Therefore, the columns corresponding to
prismatic joints will be zero.

For revolute joints, the contribution of each joint to each of the three angular
velocities is related to the orientation of the joint. If a joint e.g. is
aligned with the X-axis of the fixed frame, then it will naturally contribute
only to the angular velocity of the end-effector around the X-axis, namely the
$ \omega_x $. Therefore, we define the column of the Jacobian corresponding to
revolute joints equal to the orientation of the joint axis.


If we have used the DH convention for calculating the transformation between two
subsequent joints, then we have defined a coordinate frame whose z-axis is
aligned with the joint axis of rotation. Therefore, the orientation of the
revolute joint $ i $ is equal to the last column of the transformation matrix
$ R_o^i $.


Eventually we have:

\begin{equation}
   J_{\omega} = \begin{bmatrix} J_{\omega 1} & J_{\omega 2} & \dots & J_{\omega
      n} \end{bmatrix}  \\
\end{equation}
  where:

\begin{equation}
   J_{\omega i} = \begin{bmatrix} 0 \\ 0 \\ 0 \end{bmatrix} \\
\end{equation}
  when $ i $ is a prismatic joint, and:

\begin{equation}
   J_{\omega i} = \begin{bmatrix} Z_x \\ Z_y \\ Z_z \end{bmatrix} \\
\end{equation}
  when $ i $ is a revolute joint.
  

#### 5.1.2. LINEAR velocities

The linear velocity of the end-effector is affected by both the revolute and the
prismatic joints. The prismatic joints contribute to the linear velocity of the
end effector depending on the orientation of the joint, similar to the way that
revolute joints contribute to the angular velocities. If e.g. a prismatic joint
is oriented with the Z-axis of the fixed frame, then the velocity of the joint
results in a velocity of the end-effector along the Z-axis of the fixed frame,
and no velocity in the other two axes.

Therefore, the column of the linear Jacobian corresponding to a prismatic joint
has the form:

\begin{equation}
   J_{u i} = \begin{bmatrix} Z_x \\ Z_y \\ Z_z \end{bmatrix} 
\end{equation}


However, contrary to the angular velocities, the linear velocity of the
end-effector does not depend only on the prismatic joints. The revolute joints
have a contribution to the linear velocity of the end-effector as well. This is
similar to the way that the wheels of the car, even though they are just
rotating and not translating, they still cause a linear motion of the car.

The contribution of the revolute joints on the linear velocity of the
end-effector are related to the orientation of the joint, but also to the
distance between the joint and the end effector. This is once again similar to
the wheels of a car: the resulting linear velocity of the car depends on the
distance from the joint of rotation of the wheel and the ground. For the same
angular velocity of the wheel, we have larger linear velocity of the car for a
wheel with a bigger diameter.


Finally, the linear velocity resulting from an revolute joint is expressed as a
vector, and more specifically as the cross product between the vectors of the
axis of rotation and the vector connecting the joint origin and the
end-effector. Therefore, for revolute joints the linear Jacobian has the form:

\begin{equation}
   J_{u i} = \begin{bmatrix} z_{i} \times (o_n - o_{i-1}) \end{bmatrix}
\end{equation}

### 5.2 Inverse velocities

As with the kinematics, it is usually more useful to be able to solve the
inverse velocities problem i.e. to calculate the joint coordinates that will
result in the desired end-effector velocities. This is accomplished by
multiplying from the left with the inverse of the Jacobian both sides of our
principal equation:

\begin{equation}
   \xi = J \dot{q} \equiv J^{-1}\xi = \dot{q} 
\end{equation}


However, to be able to do this, the Jacobian must be invertible. For a matrix to
be invertible, it must satisfy two conditions:

- It must be square
- Its rank should be equal to its dimension



As we noticed above, the size of the Jacobian is $ 6 \times n $, where n is the
number of joints. Therefore, for the Jacobian to be invertible we need to have
six joints. The second condition is related to the degrees of freedom as the rank
of the Jacobian is equal to the degrees of freedom of the robot. Therefore for the
Jacobian to be invertible, the robot must not only have six joints, but also they
should be arranged in such a configuration so that they result in six degrees of
freedom.
Since the Jacobian depends on the joint coordinates, we can see that for some
set of joint coordinates, the Jacobian might lose rank and become
non-invertible. When this occurs, we say that the robot is in a
_singular_ configuration. This usually happens when two subsequent links get
aligned, and therefore the influence of one of the two joints on the
end-effector position becomes almost zero (see figure 5.1)

<center>
    <figure class="image">
      <img src="artwork/jacobian/jac1.png" width=40% />
      <figcaption>Figure 5.1: A robot in a singular configuration </figcaption>
    </figure>
</center>

#### 5.2.1. The pseudoinverse


Some times, we have robots with more than 6 joints, still resulting in a robot
with six degrees of freedom. We should be able to calculate the inverse
velocities problem since the robot has the dexterity to impose velocities in and
around all axes. However, our Jacobian is $ 6 \times 7 $ and therefore non
invertible.

To go around this problem, we calculate the pseudoinverse of the Jacobian. The
pseudoinverse is a matrix that if multiplied with the original matrix gives the
identity, just like the real inverse. We calculate it using the following
methodology:

\begin{equation}
   (JJ^T)(JJ^T)^{-1}= I \\
   J[J^T(JJ^T)^{-1}]= I \\
   JJ^+ = I \\
\end{equation}

where: 
\begin{equation}
   J^+ = J^T(JJ^T)^{-1} 
\end{equation}

### 5.3 Robopy toolbox

The robotics toolbox has some methods to calculate the jacobian of a robot,
however it is able to do that only for specific configurations. As we saw above,
the Jacobian depends on the joint orientations, which depend on the joint
angles. Therefore, the Jacobian is not a fixed quantity and the robotics toolbox
cannot calculate an analytical expression of it. Instead, it can calculate it
for specific joint coordinates.
In the following examples, we will work with a predefined robot model, namely
the __Puma560__ robot from Unimate robots. It is a SerialLink object with respective methods.

We can then calculate the Jacobian for a specific configuration
running the following command:

__p560.jacobn(T) /TBA__

whereT is a transformation matrix, describing the pose of the robot


### 5.4. Proposed problems


  1. We consider the robotic structure with 3 degrees of freedom from fig 5.2
  
  <center>
    <figure class="image">
      <img src="artwork/jacobian/jac2.png" width=40% />
      <figcaption>Figure 5.2.: Robot RRT</figcaption>
    </figure>
</center>


    a. Determine the DH parameters for the model.
    b. Determine the transformation from the fixed frame to each joint
        coordinate frame.
    c. Determine the Jacobian.
  
  
  2. Consider the Puma 560 robot in the following joint coordinates: $ q_1 = 0.1, q_2 = 0.5, q_3 = 0.1, q_4 = 0.8, q_5 = 0.1, q_6 = 0.2 $
    
    
    a. Calculate the Jacobian for this configuration using the robotics
        toolbox.
    b. Calculate the joint velocities that will result in end-effector
        linear velocity along the X-axis of 2 m/s.
    c. Calculate the resulting end-effector velocities (linear and angular)
        for joint velocities equal to:
$\dot{q} = \begin{bmatrix} 1 & 1.4 & 1.7 & 0.2 & 0.3 & 0.1 \end{bmatrix}$
    



In [3]:
import numpy as np
from robopy import *
from robopy import serial_link
import matplotlib.pyplot as plt
import math
import sympy as sym

##ex1
# q1,q2,q3 = sym.symbols("q1 q2 q3")

l1 = 1
l2 = 1
l3 = 1
q1 = 0
q2 = 0
q3 = 0

#calculating DGM
R01 = transl(l1,0,0)*trotz(q1)
R12 = trotx(pi/2)*transl(0,0,l2)*trotz(q2)
R23 = trotx(pi/2)*transl(0,0,q3)*trotz(-pi/2)
R34 = transl(0,0,l3)

#find joint respective DGMs
T4 = R01*R12*R23*R34;
T3 = R01*R12*R23;
T2 = R01*R12;
T1 = R01;


#end positions
Pn = T4[[0,1,2],3]
P1 = T1[[0,1,2],3]
P2 = T2[[0,1,2],3]
P3 = T3[[0,1,2],3]

#linear 
Ju1 = np.cross(T1[[0,1,2],2].T,np.asarray(Pn-P1).T).T;
Ju2 = np.cross(T2[[0,1,2],2].T,np.asarray(Pn-P2).T).T;
Ju3 = T3[[0,1,2],2];


#angular
Jw1 = T1[[0,1,2],2];
Jw2 = T2[[0,1,2],2];
Jw3 = np.array([[0],[0],[0]]);

Ju = np.concatenate((Ju1,Ju2,Ju3),axis=1)
Jw = np.concatenate((Jw1,Jw2,Jw3),axis=1)

J = np.concatenate((Ju, Jw))
print(J)
 
# Jplus = J.T*np.linalg.inv(J*J.T)  --> can be singular

# #eval in a certain position sith symbolic velocities //code to be rewrtitten:
# q1 = 0;
# q2 = pi/2;
# q3 = 1;
# rJ = (eval(J));
# dq1 = sym.Symbol('dq1')
# dq2 = sym.Symbol('dq2')
# dq3 = sym.Symbol('dq3')
# xi = rJ*[dq1;dq2;dq3]







[[ 1.  1.  0.]
 [ 0.  0.  0.]
 [-0.  0. -1.]
 [ 0.  0.  0.]
 [ 0. -1.  0.]
 [ 1.  0.  0.]]


In [ ]:
import numpy as np
from robopy import *
from robopy import serial_link
import matplotlib.pyplot as plt
import math

###ex2

q1=0;
q2=0;
q3=0; 
q4=0;
q5=0;
q6=0;
q = np.array([q1, q2, q3, q4, q5, q6])

p = Puma560()
T = p.fkine(q)
#to be J = p.jacobn(T)

# plot the puma
qmat = np.asmatrix(q)
p.plot(qmat, unit='rad')


#end effector velocities for qv
# qv = np.array([1, 1.4, 1.7, 0.2, 0.3, 0.1]).T;
# xi = J*qv;

# #joint velocities for end effector on Xaxis of 2m/s
# Jinv = np.linalg.inv(J)
# E    = np.array([2,0,0,0,0,0]).T;
# qv2  = Jinv*E;